### ISSUE TITLE
Keyboard Support 

### ISSUE THREAD

**Issue by jimtryon** [MichalPaszkiewicz/musicscoretrainer#5]
Currently, the game only supports clicking on the appropriate note with the mouse that matches in the treble clef.  I'd like to suggest being able to use the keyboard to select notes.  This would help keep the pace of the game moving as it can take additional time to keep moving your mouse back and forth between the letters.  For example, if the note was a C, then I'd press the C key on the keyboard or an A key for an A note.

**Comment by MichalPaszkiewicz** [comment]
I've mapped keyboard keys to notes, but I'm using a mapping that directly represents position of keys on a keyboard (since it'd be hard to press both c and a # in the harder levels).

so the mapping is as such:

a : C
w : C#
s : D
e : D#
d : E
f : F
t : F#
g : G
y : G#
h : A
u : A#
j : B

I will display the mapping in the actual program later

**Comment by jimtryon** [comment]
Thanks, I think this mapping will do the trick!

**Comment by jimtryon** [comment]
I like how you mapped it in relation to half steps and whole steps to positions on the keyboard.

**Comment by MichalPaszkiewicz** [comment]
great! glad to be of service :+1:
